# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7447d0dc7ab79876de752582b493696b9cb0cf6c96fde588cd7cc4f57b336e6703f71a416ab6fef63a49d3450c52c739e37904cbe5576487f55342ab7e24a22b

test:
  secret_key_base: f5009de0227e12f701ca0a5fb7ed64fe922d623fc3e00203480daa966052212cb09ce6ecd5e563c11ebeb8a95a65a7a60ef567742ae8b7776f811828a40f8334

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
